#!/bin/sh
set -eu

if [ "$1" = -C ]; then
  directory=$2
  shift 2
else
  directory=''
fi

case "$1" in
  init)
    for argument in "$@"; do directory=$argument; done
    mkdir -p "$directory/.git"
    ;;
  remote) ;;
  fetch) printf '%s\n' "$MOCCA_FAKE_GIT_REF" >"$directory/FETCH_HEAD" ;;
  rev-parse) cat "$directory/FETCH_HEAD" ;;
  sparse-checkout)
    if [ "$2" = set ]; then
      for argument in "$@"; do path=$argument; done
      printf '%s\n' "$path" >"$directory/.fake-git-path"
    fi
    ;;
  checkout)
    path=$(cat "$directory/.fake-git-path")
    mkdir -p "$directory/$(dirname "$path")"
    if [ -n "${MOCCA_FAKE_PROFILE_ROOT-}" ]; then
      cp -R "$MOCCA_FAKE_PROFILE_ROOT/${path##*/}" "$directory/$path"
    else
      cp -R "$MOCCA_FAKE_PROFILE" "$directory/$path"
    fi
    ;;
  *) echo "unexpected fake git command: $*" >&2; exit 1 ;;
esac
